# Generated by Django 4.1.4 on 2023-08-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_aamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='aamount',
            new_name='amount',
        ),
    ]
